### ISSUE TITLE
Add mailto near user profiles hyperlinks

### ISSUE THREAD

**Issue by fabiodrg** [msramalho/SigTools#99]
- Add a "send email" button in each individual FEUP employee hyperlink (e.g. Teacher)
- Allow to select multiple FEUP employees to send an email

My main motivation for this is when having to contact more than one teacher from search results or from course unit pages. The typical approach is to open the profile in separate pages and copy the links. With batch email I could select multiple users without that manual process. Furthermore, for single recipients, I could click one button near the user name/link without having to move to a different page to get the email.

# Tasks
- [x] Fetch the profile view page for parsing the institutional email (may not be visible). E.g., `https://sigarra.up.pt/feup/en/func_geral.formview?p_codigo=<id>`. Another possible hyperlink is `https://sigarra.up.pt/feup/pt/vld_entidades_geral.entidade_pagina?pct_codigo=<id>`. It is commonly used for students, but I have seen it for FEUP staff as well, which then redirects to `func_geral.formview`. For example, [thesis lists](https://sigarra.up.pt/feup/pt/teses.lista_teses?pv_num_pag=4&p_record_set_size=10&p_curso=742&p_lang=0&p_ord_campo=D_DEFESA_TESE&p_ordem=DESC&p_tipo_lista=C).
- [x] Add the buttons with `mailto` hyperlinks near the original hyperlink tag, i.e. `<a>`
- [x] Add an option on right-side sidebar that enables selecting multiple addresses to send the email? Useful when you want to contact more than one person. Perhaps, open a modal with all emails and enable batch selection
  - [ ] One step further: BCC + CC?
- [x] Cache the emails per user ID
- [ ] Configurable threshold. i.e., if the page has more than E email addresses, then ignore. Might be useful in search results pages with dozens of emails. Default, 15?
- [ ] Ignore hyperlinks for the logged in user?

**Comment by fabiodrg** [comment]
The issue #69 is related. Might be useful to create a `Person` parser. It should support parsing from the `document` or from a custom context (e.g. URL, html, DOMParser). That parser could be used in both issues (this one and #69)

**Comment by fabiodrg** [comment]
One more issue to handle. looks like Sigarra server responses are encoded as `text/html; charset=iso-8859-15`. As the response body is interpreted as `utf-8`, weird icons appear...

![image](https://user-images.githubusercontent.com/5472505/158885716-4389e513-a0ee-443c-b79a-433827f82417.png)


![image](https://user-images.githubusercontent.com/5472505/158885501-10062482-fda9-4ff8-bd06-e4bc553b33fd.png)

**Comment by fabiodrg** [comment]
With respect to ignoring hyperlinks associated to the logged in user.. I thought it would be easy, but it looks like the hyperlinks used to access my profile near the login form and on the top bar use yet another ID is not the user ID (student up<xxxxx> or staff identifiers)...

I could fetch that URL to gather the actual user ID, just not sure if it is worth it.
![image](https://user-images.githubusercontent.com/5472505/158981099-ea49a99c-006e-45f7-b50d-8ac8f706586d.png)
![image](https://user-images.githubusercontent.com/5472505/158981147-8f898d3e-08f2-423f-a0f3-bdebb49402e8.png)

**Comment by fabiodrg** [comment]
Found a third type of page for users in thesis lists: https://sigarra.up.pt/feup/pt/inst_geral.ver?P_CODIGO=1891
